### PR TITLE
Make editable pages for each assembly instruction packet

### PR DESCRIPTION
**Pull request by bsubbaraman**
Addresses #111 

 Changes:

- added new docs pages which include each page of the assembly pdf packets. each page has a header, so that others can add notes about their issues/changes/etc while assembling a jubilee.

### CODE REVIEW

**Comment by sgbaird** [comment]
Awesome, this looks great @bsubbaraman!

I've made a number of updates. Please have a look.

Some random notes:
- Removed "next-->" since this is taken care of with the toctrees.
- 

Do you mind taking care of the following items?
- Add descriptive titles for each of the pages image (looks like most pages should have a title at the bottom-right of the image)
- Consider adding the section 2 video links from https://jubilee3d.com/index.php?title=Assembly_Instructions on the corresponding pages
- We also want to add instructions for the electronics, firmware setup, software setup, and "first flight" checks. Maybe start off with just the electronics piece?
- Let's embed the videos where appropriate. Probably using `sphinx-contrib.youtube`. See https://chatgpt.com/share/90256551-f9e6-4755-bcc5-9c1b0d21f504.
- Any clarifications to add on later wiring for tools? (especially regarding what people purchase). Ideally, people should buy everything in one go at the beginning if they already know which tools they want to use.
- Perhaps the lab automation deck should go into the "Building a Science Jubilee" portion rather than in the "Science Jubilee Tools" portion.

**Comment by sgbaird** [comment]
I'm seeing the docs\getting_started\new_user_guide.md now.

I think building the science jubilee is sort of the "real" getting started.
image. Given the changes in this PR, might be worth thinking what might benefit from restructuring and moving.

**Comment by bsubbaraman** [comment]
Thanks for these updates @sgbaird! Bringing @brendenpelkie in to discuss reorganization since you added this helpful new user guide. 

How do we want to organize the docs? 'Getting Started' currently primarily refers to the `science-jubilee` python codebase. Should we rename 'Getting Started' to 'Using `science-jubilee` to control your machine' or something? Then maybe we can divide the New User Guide information between the 'building a jubilee' and the software sections?  I also see the utility in having a high-level end-to-end guide which gives people a sense in what needs to happen to go from nothing to an experiment.

**Comment by brendenpelkie** [comment]
Great to see this, I didn't realize this was in progress when I added the new user guide! I think we are bumping up against some tension between having these docs be for "science-jubilee, the python package for controlling Jubilee" and "science Jubilee, the place to come learn how to do experiments with Jubilee". I would advocate for leaning into the latter in our docs and making science-jubilee docs as much of a one-stop-shop for jubilee guidance as possible. Jubilee for science is really starting to get some traction in the community, and we should make sure new users have a clear path forward when getting started. There might be other organizational schemes for this that are worth considering, but we should settle on something. (ex, split the python package docs and general guidance docs). I opened #125 with the goal of discussing this. I think we should consider how to organize the entire project as well, in addition to the docs. Are we outgrowing the current setup of having everything (code, tools, config, guidance/docs) in one github repo, or is this a simple solution that gets the job done? 

Back to the original question, I think it makes sense to have an obvious landing section aimed at someone who heard about Jubilee somewhere and wants to see what it's about. This might look like the front page but with more details, maybe a text version of how we introduce Jubilee in talks/posters/etc. Then the obvious next step might be something like my 'new user guide' that gives a detailed walkthrough of how to get up and running on Jubilee, from buying the kit all the way to running an experiment. 'Getting started' might be a bit of an understatement for this section.

I'm currently onboarding 3 new Jubilee users (2 MechE students and 1 ChemE PhD student). I expect to have clearer thoughts on this in a week or so after seeing how they feel about the learning process.

**Comment by sgbaird** [comment]
Sorry it took a while to get back to this!

> Great to see this, I didn't realize this was in progress when I added the new user guide!

Thanks! That was my bad for not seeing the new user guide sooner 😅 

> I think we are bumping up against some tension between having these docs be for "science-jubilee, the python package for controlling Jubilee" and "science Jubilee, the place to come learn how to do experiments with Jubilee". I would advocate for leaning into the latter in our docs and making science-jubilee docs as much of a one-stop-shop for jubilee guidance as possible. Jubilee for science is really starting to get some traction in the community, and we should make sure new users have a clear path forward when getting started.

Agreed!

> There might be other organizational schemes for this that are worth considering, but we should settle on something. (ex, split the python package docs and general guidance docs). I opened #125 with the goal of discussing this. I think we should consider how to organize the entire project as well, in addition to the docs.

I think it's worth some careful thought and discussing. In one sense, when someone says "I'm committed to getting a Science Jubilee", there are up-front need to knows and things that are OK if it comes later. Hardware to purchase and build/electronics/firmware/testing instructions are the up-front need to knows I think.

> Are we outgrowing the current setup of having everything (code, tools, config, guidance/docs) in one github repo, or is this a simple solution that gets the job done?

It's not out of question; however, in the near-term I would caution against splitting into two GitHub repos and instead focus on finding the right organization within the GitHub repo in terms of directory structure and on the website. Hardware, electronics, software, firmware, testing, documentation, and usage instructions all have some connection with each other, so splitting it up across repositories could have some unexpected downsides, especially since it wasn't designed from the start this way.

Some examples that come to mind are [Pioreactor](https://github.com/Pioreactor/pioreactor) and [Rodeostat](https://github.com/iorodeo/potentiostat). Interestingly, Pioreactor puts their CAD files on https://www.printables.com/@Pioreactor, and has a separate repo for the [docs](https://github.com/Pioreactor/docs.pioreactor), though the website makes it feel like most things are hosted under the same blanket.

FarmBot [hosts all the CAD models on OnShape](https://express.farm.bot/v1.1/extras/cad), PCB Layout/schematic on a Google Drive (linked to on CAD page), and a [top-level GitHub organization](https://github.com/FarmBot) that hosts repositories for a web app, Python driver, Arduino firmware, etc. (i.e., anything on that organization is specific to FarmBot). They actually have an entirely separate GitHub organization dedicated to documentation with quite a few repos: https://github.com/FarmBot-Docs.

OpenFlexure has a [Gitlab organization](https://gitlab.com/openflexure/) with separation of repos:

image

Some random observations:
- In general (not just these examples), I've noticed is that often a Web UI will be in a separate repo, perhaps because it's easy to use full-repo templates
- Pioreactor, OpenFlexure, and FarmBot all have dedicated discourse forums

> Back to the original question, I think it makes sense to have an obvious landing section aimed at someone who heard about Jubilee somewhere and wants to see what it's about. This might look like the front page but with more details, maybe a text version of how we introduce Jubilee in talks/posters/etc. Then the obvious next step might be something like my 'new user guide' that gives a detailed walkthrough of how to get up and running on Jubilee, from buying the kit all the way to running an experiment.

> 'Getting started' might be a bit of an understatement for this section.

"So, you want to build a Science Jubilee" 😄 

> I'm currently onboarding 3 new Jubilee users (2 MechE students and 1 ChemE PhD student). I expect to have clearer thoughts on this in a week or so after seeing how they feel about the learning process.

Similarly, as soon as we get the 3D printed parts from Lukes Laboratory, we'll be raring to go with four Science Jubilee builds with the AC summer students.

**Pull request merged**
